# Generated by Django 4.2.30 on 2026-08-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
